FROM rust:alpine as builder

WORKDIR /app

COPY . .

RUN cargo build --release --package viewer-jellyfin

FROM alpine:latest

RUN apk add --no-cache ca-certificates

COPY --from=builder /app/target/release/viewer-jellyfin /usr/local/bin/

EXPOSE 8003

CMD ["viewer-jellyfin"]
