FROM rust:alpine as builder

WORKDIR /app

COPY . .

RUN cargo build --release --package downloader-qbittorrent

FROM alpine:latest

RUN apk add --no-cache ca-certificates

COPY --from=builder /app/target/release/downloader-qbittorrent /usr/local/bin/

EXPOSE 8002

CMD ["downloader-qbittorrent"]
