[AutoRun]
enabled=false

[BitTorrent]
Session\DefaultSavePath=/downloads
Session\IgnoreSlowTorrentsForQueueing=true
Session\MaxActiveDownloads=10
Session\MaxActiveTorrents=10
Session\MaxActiveUploads=1
Session\Port=6881
Session\QueueingSystemEnabled=true
Session\SlowTorrentsInactivityTimer=1200

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=8

[Preferences]
General\Locale=en
WebUI\Address=*
WebUI\Port=8080
